### ISSUE TITLE
confirm glance store disparity between glance hosts before alerting

### ISSUE THREAD

**Issue by nealbrown** [blueboxgroup/ursula-monitoring#43]
Best I can deduce, will need 2x glance nodes and a sensu dashboard to try to test this

**Comment by ulyssesbbg** [comment]
Hi Neal, what's happening is we get sensu alerts like "Unknown file f3aafa30-ad24-4ab6-8cb4-ab4d995cd785 found in /var/lib/glance/images" for example, on a 3.8+GB image still uploading or syncing on a particular node.  After the upload completes, the alert goes away.  The upload/sync typically completes within 5-10 minutes of the alert firing.

A few things can cause this: 1) The image might exist on the second controller and is just waiting to be auto-synced to the first controller.  This alert will fire until the sync occurs, and will then be resolved on its own.  2) The image might exist remotely and this check is unnecessary.

To fix this, you'll want to modify https://github.com/blueboxgroup/ursula-monitoring/blob/master/sensu/plugins/check-glance-store.py , and then push the fix out to the clusters and possibly restart sensu-client or other sensu services when doing so.

---

BTW - Occasionally, when an upload is cancelled before it finishes or is otherwise corrupted, we will find a tiny aborted image in /var/lib/glance/images, which will produce the same alert.  We have to manually move the image to something like /root/badglanceimages.  Would rather the on-call person not get woken up at 3AM to take care of this.  Thanks!

**Comment by nealbrown** [comment]
Ok it's going to take me some time to get a full stack + sensu dashboard going but I'll let you know asap.

**Comment by ulyssesbbg** [comment]
Hi Neal, you can use the bbg-staging-01 cluster.  You can use the production sensu dashboard and just silence the alerts for bbg-staging-01 while you're working on it.

As an alternative - it may be easier - you can also put a sensu suppression window to suppress check-glance-store alerts outside of 8AM-5PM Pacific.

**Comment by nealbrown** [comment]
Ok thanks I'll see if anyone is using it

**Comment by omgjlk** [comment]
Might be better to use bbg-support-01. staging-01 is getting wiped and rebuilt as a 2.0 (Kilo) cluster.

**Comment by nealbrown** [comment]
The existing check-glance-store is analogous to a nagios check, it runs constantly and does real time checks.  It does not track time series like we want for the "eventually correct" new glance monitor.  I'm going to look into the glance-sla monitor we have to see if that tracks time series.  This will run on the sensu server itself and not the agent.

ulyssesbbg, do we currently alert on the sla monitors, or do we want a new server side glance monitor?

**Comment by omgjlk** [comment]
Neal, couldn't we change the threshold of how many times this check fails
before it becomes "critical"?
- jlk

**Comment by nealbrown** [comment]
Doh, apologies for the delay I needlessly set up my own rabbitmq/sensu because I thought I would need to do the time series : (  PR incoming.
